matrix:
  include:
    - language: python
      sudo: false
      python:
        - "2.7"
      cache:
        directories:
          - "~/.platformio"
      install:
        - pip install -U platformio
        - platformio update
      script:
        - platformio run
      os:
        - linux
    - language: cpp
      compiler:
        - g++
      script: cd tests && make && make test
      os:
        - linux
